### ISSUE TITLE
Wrong table_alias when parsing '...inner join...'

### ISSUE THREAD

**Issue by bkiers** [bkiers/sqlite-parser#1]
When parsing:

```sql
Select firstName, LastName from Visit  
inner join Person on (Person.personId = Visit.personId) 
inner join VisitRole on (Visit.visitId = VisitRole.visitID)
```

`inner` gets parsed as a `table_alias` for `Visit`.

**Comment by TheSylence** [comment]
I managed to fix this by changing the definition of `table_alias` to
```
table_alias
 : IDENTIFIER
 | STRING_LITERAL
 | '(' table_alias ')'
 ;
```
effectively removing `keyword` (which is included in `any_name`) from the definition

**Comment by bkiers** [comment]
Thanks @TheSylence, merged your fix in `master`.
