### ISSUE TITLE
incomplete parse tree for order by clause

### ISSUE THREAD

**Issue by PatrickEricx** [bkiers/sqlite-parser#19]
Hi Bart, 
thanks for this great work.
Working with antlr-4.7-complete.jar, When I make a separate rule for "order by", to make smaller testable pieces of code
K_ORDER K_BY ordering_term ( ',' ordering_term )* 
the first test with only 1 ordering_term goes fine, but if I add a second ordering_term, it is parsed without error, but I don't see it in the tree.
I tested both variants of the grammar, with a defined token and hard coded value for comma.
order_by_clause
 :  K_ORDER_BY ordering_term ( COMMA ordering_term )*
;

and 
order_by_clause
 :  K_ORDER_BY ordering_term ( ',' ordering_term )*
;
C:\work>java org.antlr.v4.gui.TestRig <packagename>Sql order_by_clause -tree
ORDER BY bananas
^Z
(order_by_clause ORDER BY (ordering_term (expr (column_name bananas))))
==> test 1: OK.

C:\work>java org.antlr.v4.gui.TestRig <packagename>Sql order_by_clause -tree
ORDER BY bananas, apples
^Z
(order_by_clause ORDER BY (ordering_term (expr (column_name bananas))))
==> test2: missing expression in the parse tree.

Is this a bug, or is this expected behaviour?
Thanks,
Patrick Ericx

**Comment by bkiers** [comment]
Hi Patrick, a bit of a late reply... Does it also happen when you force the `order_by_clause` to consume the entire input? You can do this by adding an `EOF` at the end of the rule:

```
order_by_clause
 : K_ORDER_BY ordering_term ( ',' ordering_term )* EOF
 ;
``` 

?

**Comment by PatrickEricx** [comment]
Hi Bart, thanks for your reply. Without changing anything on the code, but after a recompile, I get the tree as expected. So I close the issue. I will keep your suggestion of EOF in mind for later reference. Best regards, Patrick Ericx.

**Comment by bkiers** [comment]
👍
