### ISSUE TITLE
Add JAVA_TOOL_OPTIONS setting in README.md

### ISSUE THREAD

**Issue by kjetillll** [bkiers/sqlite-parser#20]
Running `mvn clean test` took 18 min (not 2) and I tried a lot before finding `export JAVA_TOOL_OPTIONS="-Xmx2048m -Xms256m"` as an antidote to "java.lang.OutOfMemoryError: Java heap space" at around 6400 tests (out of 19559).

If that export command have been mentioned in README.md right before `mvn clean test` it would have saved me and perhaps others much time&effort.

**Comment by bkiers** [comment]
Removed the 2 minutes and added a comment about increasing the heap: https://github.com/bkiers/sqlite-parser/commit/9adf75ff5eca36f6e541594d2e062349f9ced654

**Comment by kjetillll** [comment]
I see your change now, but `-Xms256m` was also needed for me for `mvn clean test` not to crash. The problem wasn't about the time spent, it was about the two points it crashed: at about 6400 and 6600 tests.

**Comment by bkiers** [comment]
It did't crash on my machine without the `-Xms` argument. Instead, it took much longer on my machine with the `-Xms` argument.
