### ISSUE TITLE
Validity of SQL Query

### ISSUE THREAD

**Issue by Mrs-Hudson** [bkiers/sqlite-parser#5]
When I input an invalid query to Main.java (such as 'select log as x') the lexer and parser work without checking the validity of the query.

**Comment by bkiers** [comment]
The input `select log as x` is being parsed as:

```
(select_stmt 
  (select_or_values select 
    (result_column 
      (expr 
        (column_name (any_name log))) 
    as (column_alias x))))
```

Could you indicate why this is wrong? Seems to be inline with the specs:

![select-stmt](https://www.sqlite.org/images/syntax/select-stmt.gif)

**Comment by Mrs-Hudson** [comment]
The complete query would be SELECT log as x from table_name. So shouldn't the grammar parse this query and realise it is invalid?

**Comment by bkiers** [comment]
No, the `FROM` clause is optional as you can see from the railroad diagram:

![select-stmt](https://cloud.githubusercontent.com/assets/281616/7019871/94b5761c-dd14-11e4-8dd2-e9fedf89d55d.png)

**Comment by Mrs-Hudson** [comment]
Okay, thanks a lot! :)

**Comment by Mrs-Hudson** [comment]
As per the railroad diagram, the below query will parse:
SELECT city, id from table group by city

But it is incorrect as the id column should be included in GROUP clause or be acted upon by an aggregate function.

**Comment by bkiers** [comment]
Such semantic checks are done by the developer *after* parsing (i.e. in a listener or visitor). The ANTLR grammar follows the official syntax from the SQLite diagrams as closely as possible. Just as checking types/validity of expressions: this is not handled by the grammar, but is done after parsing. There are many more of such cases.
