### ISSUE TITLE
Left Recursion in column_def

### ISSUE THREAD

**Issue by AlecStrong** [bkiers/sqlite-parser#6]
Thanks for the grammar! It's been incredibly useful.

I noticed a left recursion in column_def:
```
column_def
 : column_name type_name? column_constraint*
 ;
```

type_name resolves to
```
type_name
 : name+ ( '(' signed_number ')'
         | '(' signed_number ',' signed_number ')' )?
 ;
```

and since `name` resolves to anything it ends up parsing constraints as a string of `type_name`s.

Example:

```
CREATE TABLE table(
  _ID TEXT NOT NULL PRIMARY KEY
)
```

parses down to
```
create_table_stmt
--table_name
--column_def
----column_name
----type_name
------name (TEXT)
------name (NOT)
------name (NULL)
------name (PRIMARY)
------name (KEY)
```

when I'm expected `NOT NULL` and `PRIMARY KEY` to be parsed as `column_constraint`s

I've remedied this locally by changing the definition for type_name to
```
type_name
 : name ( '(' signed_number ')'
         | '(' signed_number ',' signed_number ')' )?
 ;
```

but i could see this having bad consequences elsewhere (expecting multiple `name`s when this only allows one)

I'm also not sure if this is just a limitation of LL parsers on sqlite. 

Again, thanks for the grammar!

**Comment by bkiers** [comment]
Hi Alec, thanks, I will have a look at this.
